### PR TITLE
Version change to 0.2.6

### PR DESCRIPTION
**Pull request by afck**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/lru_time_cache/54)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
Thanks for the pull request, and welcome! The MaidSafe team is excited to review your changes, and you should hear from @Fraser999 (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. The way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [CONTRIBUTOR.md](../blob/master/CONTRIBUTOR) for more information.

**Comment by afck** [comment]
I also increased the version number.
We'll need to use this feature when we port Routing to Crust 0.9.0.

**Comment by Fraser999** [comment]
Sorry Andreas, could you do the version increase as a separate PR please with the title `Version change to 0.2.6`

We use the merging of a version change PR to master as the trigger for generating and publishing updated docs, and the version change PRs generally have no changes other than the toml, changelog and possibly the readme (if the todo list has been updated).

Feel free to close this PR and submit two new ones, or update this one to remove the version change commit.

**Comment by afck** [comment]
I moved the non-`Clone` part to #55.

**Pull request closed without merging**
