### PR TITLE
Version change to 0.2.0

### PR DESCRIPTION
**Pull request by chandraprakash**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/lru_time_cache/26)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @dirvine

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by chandraprakash** [comment]
Looks like Jenkins config issue. @Fraser999

**Comment by chandraprakash** [comment]
@Fraser999  this looks like Jenkins failure. help please :-)

**Comment by Fraser999** [comment]
@chandraprakash Thanks for the heads-up.  This was a bug in the Jenkins script which is fixed now.  I've re-run the jenkins-ci-win64 task and it passed (http://ci.maidsafe.net:8080/job/lru_time_cache_win64/19/) but it doesn't auto-update the status link here unfortunately.  Regardless - this now passes all CI tests.

**Comment by chandraprakash** [comment]
Thanks Fraser !

**Comment by Viv-Rajkumar** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/lru_time_cache/26)

**Pull request merged**
