### PR TITLE
Initial run of RustFmt

### PR DESCRIPTION
**Pull request by rosatamsen**
**Code Bounty task**
Initial run of RustFmt on libraries that are not being worked on at the moment.

**My bitcoin address:** 1KfJGj4j8iYdywwgZGkwsVZngaSXkTX6XL

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/lru_time_cache/36)

### CODE REVIEW

**Comment by rosatamsen** [comment]
Hi @chandraprakash, just wanted to let you know my PR didn't get automatically assigned to anyone.

**Comment by rossmuir** [comment]
@rosatamsen  I have assigned this PR a reviewer. Thanks

**Comment by dirvine** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/lru_time_cache/36)

**Comment by rosatamsen** [comment]
@NickLambert Just letting you know, in case you missed this one.

**Comment by NickLambert** [comment]
Got it, thanks. BTC will be with you shortly. Thanks again!

**Pull request merged**
